name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.6'
      - run: go build
      - uses: actions/upload-artifact@v1
      with:
        name: bonjwa-schedule-api
        path: bonjwa-schedule-api
